name: NASA Project CI
on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      - name: Use Node.js version 18.0
        uses: actions/setup-node@v3
        with:
          node-version: '18.0'
      - run: npm install
      - run: npm run build --prefix client